spring:
  application:
    name: demoCiCd

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true
    username: postgres.egwwpaoacecgkdaycggp
    password: UmangMehla@6228
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0
